"""Testing components for recording, replaying, and validating agent runs."""

from nanoharness.testing.trace import (
    TRACE_SCHEMA_VERSION,
    AgentTrace,
    TraceEvent,
    TraceEventType,
    TraceRecorder,
    normalize_trace_value,
    redact_sensitive_fields,
)
from nanoharness.testing.replay import (
    InvalidTraceError,
    RecordedExecutionError,
    RecordingLLM,
    RecordingToolRegistry,
    ReplayError,
    ReplayExhaustedError,
    ReplayLLM,
    ReplayMismatchError,
    ReplaySession,
    ReplayToolRegistry,
    UnconsumedReplayEventsError,
    UnsupportedTraceVersionError,
)
from nanoharness.testing.oracle import (
    OracleConfigurationError,
    OracleContext,
    OracleEvaluator,
)
from nanoharness.testing.runner import ScenarioRunner
from nanoharness.testing.scenario import (
    SCENARIO_SCHEMA_VERSION,
    ExecutionError,
    OracleKind,
    OracleSeverity,
    OracleSpec,
    OracleVerdict,
    Scenario,
    ScenarioAssertionError,
    ScenarioReport,
    UnsupportedScenarioVersionError,
)

__all__ = [
    "TRACE_SCHEMA_VERSION",
    "AgentTrace",
    "TraceEvent",
    "TraceEventType",
    "TraceRecorder",
    "normalize_trace_value",
    "redact_sensitive_fields",
    "RecordedExecutionError",
    "InvalidTraceError",
    "RecordingLLM",
    "RecordingToolRegistry",
    "ReplayError",
    "ReplayExhaustedError",
    "ReplayLLM",
    "ReplayMismatchError",
    "ReplaySession",
    "ReplayToolRegistry",
    "UnconsumedReplayEventsError",
    "UnsupportedTraceVersionError",
    "OracleConfigurationError",
    "OracleContext",
    "OracleEvaluator",
    "ScenarioRunner",
    "SCENARIO_SCHEMA_VERSION",
    "ExecutionError",
    "OracleKind",
    "OracleSeverity",
    "OracleSpec",
    "OracleVerdict",
    "Scenario",
    "ScenarioAssertionError",
    "ScenarioReport",
    "UnsupportedScenarioVersionError",
]
